---
- name: Update subscription manager
  command: subscription-manager refresh

- name: Install 
  become_user: root
  yum:
    name: 
      - yum-utils
      - java-11-openjdk-devel

- name: Install docker 
  command: yum install -y docker

- name: max_map 
  command: sysctl -w vm.max_map_count=262144

- name: file-max 
  command: sysctl fs.file-max

- name: enable docker
  service:
    name: docker
    enabled: true
    state: started

- name:  Create a volume
  command: docker volume create --name sonarqube_data

- name:  Create a volume
  command: docker volume create --name sonarqube_logs

- name: Create a volume
  command: docker volume create --name sonarqube_extensions

- name:  Start the SonarQube container
  command: docker run -d --security-opt seccomp=unconfined --name sonarqube \
    -p 9000:9000 \
    -e SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar \
    -e SONAR_JDBC_USERNAME=sonar \
    -e SONAR_JDBC_PASSWORD=sonar \
    -v sonarqube_data:/opt/sonarqube/data \
    -v sonarqube_extensions:/opt/sonarqube/extensions \
    -v sonarqube_logs:/opt/sonarqube/logs \ 
    sonarqube:latest

