# ---
# # Prep the Server With Required Softwares

- name: Update subscription manager
  command: subscription-manager refresh

- name: Install 
  become_user: root
  yum:
    name: 
      - yum-utils

- name: Install docker 
  command: yum install -y docker

- name: enable docker
  service:
    name: docker
    enabled: true
    state: started

- name:  Create a volume
  command: docker volume create --name sonarqube_data

- name:  Create a volume
  command: docker volume create --name sonarqube_logs

- name: Create a volume
  command: docker volume create --name sonarqube_extensions

- name:  Start the SonarQube container
  command: docker run -d --name sonarqube \
    -p 9000:9000 \
    -e SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar \
    -e SONAR_JDBC_USERNAME=sonar \
    -e SONAR_JDBC_PASSWORD=sonar \
    -v sonarqube_data:/opt/sonarqube/data \
    -v sonarqube_extensions:/opt/sonarqube/extensions \
    -v sonarqube_logs:/opt/sonarqube/logs \ 
    sonarqube:latest

# - name: make vault.service
#   blockinfile:
#     dest: /tmp/docker-compose.yml
#     marker: ""
#     block: |
#         version: "3"
        
#         services:
#           sonarqube:
#             image: sonarqube:community
#             depends_on:
#               - db
#             environment:
#               SONAR_JDBC_URL: jdbc:postgresql://localhost/sonar
#               SONAR_JDBC_USERNAME: sonar
#               SONAR_JDBC_PASSWORD: password
#             volumes:
#               - sonarqube_data:/opt/sonarqube/data
#               - sonarqube_extensions:/opt/sonarqube/extensions
#               - sonarqube_logs:/opt/sonarqube/logs
#             ports:
#               - "9000:9000"
#           db:
#             image: postgres:12
#             environment:
#               POSTGRES_USER: sonar
#               POSTGRES_PASSWORD: sonar
#             volumes:
#               - postgresql:/var/lib/postgresql
#               - postgresql_data:/var/lib/postgresql/data
        
#         volumes:
#           sonarqube_data:
#           sonarqube_extensions:
#           sonarqube_logs:
#           postgresql:
#           postgresql_data:
#     create: yes

# - name: Compose
#   command: docker compose /tmp/docker-compose.yml