---
dependency:
  name: galaxy
driver:
  name: vmware
  vcenter_hostname: ${VCENTER_HOSTNAME}
  vcenter_username: ${VCENTER_USERNAME}
  vcenter_password: ${VCENTER_PASSWORD}
  validate_certs: false
  datacenter: Cardiff
  esxi_hostname: 192.168.1.102
  folder: /Ansible/molecule/harrison
  vm_username: root
  vm_password: Renegade187!
  instance_os_type: linux  # is possible only specify [linux or windows]
  # The below are possible parameters to be specified if using the windows template.
  #winrm_port: 5986 # is WinRM port
  #connection: winrm # is the connection type
  #winrm_transport: ntlm # is the authentication type
  #winrm_server_cert_validation: ignore # is the server certificate validation mode
  # The below list is possible to define DNS nameservers
platforms:
  - name: h-Vault
    template: RHEL79-Thin
    hardware:
      num_cpus: 2 
      memory_mb: 2048
    networks:
      - name: VM Network 
        type: dhcp
    group: dhcp
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
